.TH HELP 1 "March 2025" "Version 1.0" "Key Bindings"
.SH NAME
help \- CFileManager
.SH DESCRIPTION
Manual on keyboard shortcuts for file manager

.SH CONTROLS
.TP
.B [K/J]
Navigate up/down.
.TP
.B [Enter/L]
Open selected file or directory.
.TP
.B [H]
Go back.
.TP
.B [Alt + U]
Toggle hidden files visibility.
.TP
.B [Alt + H]
Go to home dir
.TP
.B [T]
Create a new file.
.TP
.B [Shift + D]
Create a new directory.
.TP
.B [D]
Delete the selected file or directory.
.TP
.B [Q]
Quit the application.

.SH AUTHOR
Written by yinmus 

.SH GITHUB
AUTHOR:

https://github.com/yinmus

IFM:

https://github.com/yinmus/ifm

CFM:

https://github.com/yinmus/cfm
