// icons.h
// by yinmus
// MIT License

// Copyright (c) 2025 IFM-YINMUS

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// GITHUB: https://github.com/yinmus/ifm

#ifndef ICONS_H
#define ICONS_H

#include <string.h>

typedef struct {
    const char *extension;
    const char *icon;
} IconMapping;

static const IconMapping icon_mappings[] = {
    {"txt", ""},
    {"c", ""},
    {"py", ""},
    {"7z", ""},
    {"a", ""},
    {"ai", ""},
    {"apk", ""},
    {"asm", " "},
    {"asp", " "},
    {"aup", ""},
    {"avi", ""},
    {"awk", ""},
    {"bash", ""},
    {"bat", ""},
    {"bmp", ""},
    {"bz2", ""},
    {"c++", ""},
    {"cab", ""},
    {"cbr", ""},
    {"cbz", ""},
    {"cc", ""},
    {"class", ""},
    {"clj", ""},
    {"cljc", ""},
    {"cljs", ""},
    {"cmake", ""},
    {"coffee", ""},
    {"conf", ""},
    {"cp", ""},
    {"cpio", ""},
    {"cpp", ""},
    {"cs", "󰌛"},
    {"csh", ""},
    {"css", ""},
    {"cue", ""},
    {"cvs", ""},
    {"cxx", ""},
    {"d", ""},
    {"dart", ""},
    {"db", ""},
    {"deb", ""},
    {"diff", ""},
    {"dll", ""},
    {"wps", ""},
    {"wpt", ""},
    {"doc", ""},
    {"docx", ""},
    {"docm", ""},
    {"dotx", ""},
    {"dotm", ""},
    {"dump", ""},
    {"edn", ""},
    {"eex", ""},
    {"efi", ""},
    {"ejs", ""},
    {"elf", ""},
    {"elm", ""},
    {"epub", ""},
    {"erl", ""},
    {"ex", ""},
    {"exe", ""},
    {"exs", ""},
    {"f#", ""},
    {"fifo", "󰟥"},
    {"fish", ""},
    {"flac", ""},
    {"flv", ""},
    {"fs", ""},
    {"fsi", ""},
    {"fsscript", ""},
    {"fsx", ""},
    {"gem", ""},
    {"gemspec", ""},
    {"gif", ""},
    {"go", ""},
    {"gz", ""},
    {"gzip", ""},
    {"h", ""},
    {"haml", ""},
    {"hbs", ""},
    {"hh", ""},
    {"hpp", ""},
    {"hrl", ""},
    {"hs", ""},
    {"htaccess", ""},
    {"htm", ""},
    {"html", ""},
    {"htpasswd", ""},
    {"hxx", ""},
    {"ico", ""},
    {"img", ""},
    {"ini", ""},
    {"ipynb", ""},
    {"iso", ""},
    {"jar", ""},
    {"java", ""},
    {"jl", ""},
    {"jpeg", ""},
    {"jpg", ""},
    {"js", ""},
    {"json", ""},
    {"jsonc", ""},
    {"jsx", ""},
    {"key", ""},
    {"ksh", ""},
    {"leex", ""},
    {"less", ""},
    {"lha", ""},
    {"lhs", ""},
    {"log", ""},
    {"lua", ""},
    {"lz", ""},
    {"lzh", ""},
    {"lzma", ""},
    {"m4a", ""},
    {"m4v", ""},
    {"markdown", ""},
    {"md", ""},
    {"mdx", ""},
    {"mjs", ""},
    {"mka", ""},
    {"mkv", ""},
    {"ml", "λ"},
    {"mli", "λ"},
    {"mov", ""},
    {"mp3", ""},
    {"mp4", ""},
    {"mpeg", ""},
    {"mpg", ""},
    {"msi", ""},
    {"mustache", ""},
    {"nix", ""},
    {"o", ""},
    {"ogg", ""},
    {"opus", ""},
    {"part", ""},
    {"pdf", ""},
    {"php", ""},
    {"pl", ""},
    {"pm", ""},
    {"png", ""},
    {"pp", ""},
    {"dps", ""},
    {"dpt", ""},
    {"ppt", ""},
    {"pptx", ""},
    {"pptm", ""},
    {"pot", ""},
    {"potx", ""},
    {"potm", ""},
    {"pps", ""},
    {"ppsx", ""},
    {"ppsm", ""},
    {"ps1", ""},
    {"psb", ""},
    {"psd", ""},
    {"pub", ""},
    {"py", ""},
    {"pyc", ""},
    {"pyd", ""},
    {"pyo", ""},
    {"r", "󰟔"},
    {"rake", ""},
    {"rar", ""},
    {"rb", ""},
    {"rc", ""},
    {"rlib", ""},
    {"rmd", ""},
    {"rom", ""},
    {"rpm", ""},
    {"rproj", "󰗆"},
    {"rs", ""},
    {"rss", ""},
    {"rtf", ""},
    {"s", ""},
    {"sass", ""},
    {"scala", ""},
    {"scss", ""},
    {"sh", ""},
    {"slim", ""},
    {"sln", ""},
    {"so", ""},
    {"sql", ""},
    {"styl", ""},
    {"suo", ""},
    {"svelte", ""},
    {"swift", ""},
    {"t", ""},
    {"tar", ""},
    {"tex", "󰙩"},
    {"tgz", ""},
    {"toml", ""},
    {"torrent", ""},
    {"ts", ""},
    {"tsx", ""},
    {"twig", ""},
    {"vim", ""},
    {"vimrc", ""},
    {"vue", "󰡄"},
    {"wav", ""},
    {"webm", ""},
    {"webmanifest", ""},
    {"webp", ""},
    {"xbps", ""},
    {"xcplayground", ""},
    {"xhtml", ""},
    {"et", "󰈛"},
    {"ett", "󰈛"},
    {"xls", "󰈛"},
    {"xlt", "󰈛"},
    {"xlsx", "󰈛"},
    {"xlsm", "󰈛"},
    {"xlsb", "󰈛"},
    {"xltx", "󰈛"},
    {"xltm", "󰈛"},
    {"xla", "󰈛"},
    {"xlam", "󰈛"},
    {"xml", ""},
    {"xul", ""},
    {"xz", ""},
    {"yaml", ""},
    {"yml", ""},
    {"zip", ""},
    {"zsh", ""},
};

const char *icon_ext(const char *extension) {
    for (size_t i = 0; i < sizeof(icon_mappings) / sizeof(icon_mappings[0]); i++) {
        if (!strcasecmp(extension, icon_mappings[i].extension)) {
            return icon_mappings[i].icon;
        }
    }
    return "";
}

#endif 
