/*
======================================
    IFM by yinmus (c) 2025-2025
======================================

Relative path : ifm/src/icons.h
Github url : https://github.com/yinmus/ifm.git
License : GPLv3

*/

#ifndef ICONS_H
#define ICONS_H

#include <string.h>

typedef struct {
  const char* extension;
  const char* icon;
  const char* color;
} IconMapping;

static const IconMapping icon_mappings[] = {{"txt", "󰈙", "#7ecd4d"},
                                            {"c", "", "#5391e9"},
                                            {"py", "", "#ebaf0c"},
                                            {"7z", "", "#ffa500"},
                                            {"a", "", NULL},
                                            {"ai", "", "#ff7f00"},
                                            {"apk", "", "#3ddc84"},
                                            {"asm", " ", NULL},
                                            {"asp", " ", NULL},
                                            {"aup", "", "#04a1eb"},
                                            {"avi", "", "#ff5555"},
                                            {"awk", "", NULL},
                                            {"bash", "", "#7fce4f"},
                                            {"bat", "", NULL},
                                            {"bmp", "", NULL},
                                            {"bz2", "", "#ffa500"},
                                            {"c++", "", "#f34b7d"},
                                            {"cab", "", "#ffa500"},
                                            {"cbr", "", "#ff5555"},
                                            {"cbz", "", "#ff5555"},
                                            {"cc", "", "#f34b7d"},
                                            {"class", "", NULL},
                                            {"svg", "󰜡", "#ffb13b"},
                                            {"clj", "", "#db5855"},
                                            {"cljc", "", "#db5855"},
                                            {"cljs", "", "#db5855"},
                                            {"cmake", "", NULL},
                                            {"coffee", "", "#244776"},
                                            {"conf", "", "#66777f"},
                                            {"cfg", "", "#66777f"},
                                            {"cp", "", "#f34b7d"},
                                            {"cpio", "", "#ffa500"},
                                            {"cpp", "", "#f34b7d"},
                                            {"cs", "󰌛", "#178600"},
                                            {"csh", "", NULL},
                                            {"css", "", "#563d7c"},
                                            {"cue", "", "#04a1eb"},
                                            {"cvs", "", NULL},
                                            {"cxx", "", "#f34b7d"},
                                            {"d", "", "#ba595e"},
                                            {"dart", "", "#00B4AB"},
                                            {"db", "", NULL},
                                            {"deb", "", "#ffa500"},
                                            {"diff", "", NULL},
                                            {"dll", "", NULL},
                                            {"wps", "", "#0078d7"},
                                            {"wpt", "", "#0078d7"},
                                            {"doc", "", "#0078d7"},
                                            {"docx", "", "#0078d7"},
                                            {"docm", "", "#0078d7"},
                                            {"dotx", "", "#0078d7"},
                                            {"dotm", "", "#0078d7"},
                                            {"dump", "", NULL},
                                            {"edn", "", "#db5855"},
                                            {"eex", "", "#6e4a7e"},
                                            {"efi", "", NULL},
                                            {"ejs", "", "#a91e50"},
                                            {"elf", "", NULL},
                                            {"elm", "", "#60B5CC"},
                                            {"epub", "", "#7a0d21"},
                                            {"erl", "", "#B83998"},
                                            {"ex", "", "#6e4a7e"},
                                            {"exe", "", NULL},
                                            {"exs", "", "#6e4a7e"},
                                            {"f#", "", "#378BBA"},
                                            {"fifo", "󰟥", NULL},
                                            {"fish", "", NULL},
                                            {"flac", "", "#04a1eb"},
                                            {"flv", "", "#ff5555"},
                                            {"fs", "", "#378BBA"},
                                            {"fsi", "", "#378BBA"},
                                            {"fsscript", "", "#378BBA"},
                                            {"fsx", "", "#378BBA"},
                                            {"gem", "", "#ffa500"},
                                            {"gemspec", "", "#701516"},
                                            {"gif", "", "#ffb13b"},
                                            {"go", "", "#00ADD8"},
                                            {"gz", "", "#ffa500"},
                                            {"gzip", "", "#ffa500"},
                                            {"h", "", "#926ab3"},
                                            {"haml", "", "#a91e50"},
                                            {"hbs", "", "#f0772b"},
                                            {"hh", "", "#5555ff"},
                                            {"hpp", "", "#f34b7d"},
                                            {"hrl", "", "#B83998"},
                                            {"hs", "", "#5e5086"},
                                            {"htaccess", "", NULL},
                                            {"htm", "", "#e34c26"},
                                            {"html", "", "#e34c26"},
                                            {"htpasswd", "", NULL},
                                            {"hxx", "", "#5555ff"},
                                            {"ico", "", "#ffb13b"},
                                            {"img", "", NULL},
                                            {"ini", "", NULL},
                                            {"ipynb", "", "#DA5B0B"},
                                            {"iso", "", "#bdadb7"},
                                            {"jar", "", "#5382A1"},
                                            {"java", "", "#5382A1"},
                                            {"jl", "", "#a270ba"},
                                            {"jpeg", "", "#946cb6"},
                                            {"jpg", "", "#946cb6"},
                                            {"js", "", "#f1e05a"},
                                            {"json", "", "#f1e05a"},
                                            {"jsonc", "", "#f1e05a"},
                                            {"jsx", "", "#61dafb"},
                                            {"key", "", "#b5b5b5"},
                                            {"ksh", "", NULL},
                                            {"leex", "", "#6e4a7e"},
                                            {"less", "", "#1d365d"},
                                            {"lha", "", "#ffa500"},
                                            {"lhs", "", "#5e5086"},
                                            {"log", "󰌱", NULL},
                                            {"lua", "", "#000080"},
                                            {"lz", "", "#ffa500"},
                                            {"lzh", "", "#ffa500"},
                                            {"lzma", "", "#ffa500"},
                                            {"m4a", "", "#04a1eb"},
                                            {"m4v", "", "#ff5555"},
                                            {"markdown", "", "#083fa1"},
                                            {"md", "", "#083fa1"},
                                            {"mdx", "", "#083fa1"},
                                            {"mjs", "", "#f1e05a"},
                                            {"mka", "", "#04a1eb"},
                                            {"mkv", "", "#ff5555"},
                                            {"ml", "λ", "#3be133"},
                                            {"mli", "λ", "#3be133"},
                                            {"mov", "", "#ff5555"},
                                            {"mp3", "", "#029fe9"},
                                            {"mp4", "", "#ff5555"},
                                            {"mpeg", "", "#ff5555"},
                                            {"mpg", "", "#ff5555"},
                                            {"msi", "", NULL},
                                            {"mustache", "", "#f0772b"},
                                            {"nix", "", "#7ebae4"},
                                            {"o", "", NULL},
                                            {"ogg", "", "#04a1eb"},
                                            {"opus", "", "#04a1eb"},
                                            {"part", "", NULL},
                                            {"pdf", "", "#ff0000"},
                                            {"php", "", "#4F5D95"},
                                            {"pl", "", "#0298c3"},
                                            {"pm", "", "#0298c3"},
                                            {"png", "", "#946cb6"},
                                            {"pp", "", "#DA5B0B"},
                                            {"dps", "", "#d24726"},
                                            {"dpt", "", "#d24726"},
                                            {"ppt", "", "#d24726"},
                                            {"pptx", "", "#d24726"},
                                            {"pptm", "", "#d24726"},
                                            {"pot", "", "#d24726"},
                                            {"potx", "", "#d24726"},
                                            {"potm", "", "#d24726"},
                                            {"pps", "", "#d24726"},
                                            {"ppsx", "", "#d24726"},
                                            {"ppsm", "", "#d24726"},
                                            {"ps1", "", NULL},
                                            {"psb", "", "#31a8ff"},
                                            {"psd", "", "#31a8ff"},
                                            {"pub", "", "#b5b5b5"},
                                            {"py", "", "#3572A5"},
                                            {"pyc", "", "#3572A5"},
                                            {"pyd", "", "#3572A5"},
                                            {"pyo", "", "#3572A5"},
                                            {"r", "󰟔", "#198CE7"},
                                            {"rake", "", "#701516"},
                                            {"rar", "", "#ffa500"},
                                            {"rb", "", "#701516"},
                                            {"rc", "", NULL},
                                            {"rlib", "", "#dea584"},
                                            {"rmd", "", "#083fa1"},
                                            {"rom", "", NULL},
                                            {"rpm", "", "#ffa500"},
                                            {"rproj", "󰗆", "#358a5b"},
                                            {"rs", "", "#dea584"},
                                            {"rss", "", "#f26522"},
                                            {"rtf", "", "#0078d7"},
                                            {"s", "", NULL},
                                            {"sass", "", "#a53c70"},
                                            {"scala", "", "#c22d40"},
                                            {"scss", "", "#a53c70"},
                                            {"sh", "", "#48545a"},
                                            {"slim", "", "#a91e50"},
                                            {"sln", "", NULL},
                                            {"so", "", NULL},
                                            {"sql", "", NULL},
                                            {"styl", "", "#8dc149"},
                                            {"suo", "", NULL},
                                            {"svelte", "", "#ff3e00"},
                                            {"swift", "", "#F05138"},
                                            {"t", "", "#0298c3"},
                                            {"tar", "", "#ffa500"},
                                            {"tex", "󰙩", "#3D6117"},
                                            {"tgz", "", "#ffa500"},
                                            {"toml", "", "#64757d"},
                                            {"torrent", "", "#3fba9a"},
                                            {"ts", "", "#3178c6"},
                                            {"tsx", "", "#61dafb"},
                                            {"twig", "", "#83c167"},
                                            {"vim", "", "#199f4b"},
                                            {"vimrc", "", "#199f4b"},
                                            {"vue", "󰡄", "#41b883"},
                                            {"wav", "", "#029fe9"},
                                            {"webm", "", "#ff5555"},
                                            {"webmanifest", "", "#f1e05a"},
                                            {"webp", "", "#ffb13b"},
                                            {"xbps", "", "#ffa500"},
                                            {"xcplayground", "", "#F05138"},
                                            {"xhtml", "", "#e34c26"},
                                            {"et", "󰈛", "#217346"},
                                            {"ett", "󰈛", "#217346"},
                                            {"xls", "󰈛", "#217346"},
                                            {"xlt", "󰈛", "#217346"},
                                            {"xlsx", "󰈛", "#217346"},
                                            {"xlsm", "󰈛", "#217346"},
                                            {"xlsb", "󰈛", "#217346"},
                                            {"xltx", "󰈛", "#217346"},
                                            {"xltm", "󰈛", "#217346"},
                                            {"xla", "󰈛", "#217346"},
                                            {"xlam", "󰈛", "#217346"},
                                            {"xml", "", "#e34c26"},
                                            {"xul", "", "#e34c26"},
                                            {"xz", "", "#ffa500"},
                                            {"yaml", "", NULL},
                                            {"yml", "", NULL},
                                            {"zip", "", "#ffa500"},
                                            {"zsh", "", NULL},
                                            {"gitconfig", "", "#e04828"},
                                            {"xinitrc", "", "#d2491c"},
                                            {"Xauthority", "", "#d2491c"},
                                            {"Xresources", "", "#d2491c"},
                                            {"bash_profile", "", "#7dcc4d"},
                                            {"bashrc", "", "#7dcc4d"},
                                            {"viminfo", "", "#199f4b"},
                                            {"zprofile", "", "#7dcc4d"},
                                            {"zshenv", "", "#7dcc4d"},
                                            {"zshrc", "", "#7dcc4d"},
                                            {"zsh_history", "", "#7dcc4d"},
                                            {"ttf", "", "#d7d7d8"},
                                            {"otf", "", "#d7d7d8"},
                                            {"woff", "", "#d7d7d8"},
                                            {"woff2", "", "#d7d7d8"},
                                            {"eot", "", "#d7d7d8"},
                                            {"ttc", "", "#d7d7d8"},
                                            {"pfa", "", "#d7d7d8"},
                                            {"pfb", "", "#d7d7d8"},
                                            {"pfm", "", "#d7d7d8"},
                                            {"pfr", "", "#d7d7d8"},
                                            {"0", "", "#e9e9eb"}};

typedef struct {
  const char* icon;
  const char* color;
} IconResult;

IconResult icon_ext(const char* extension) {
  for (size_t i = 0; i < sizeof(icon_mappings) / sizeof(icon_mappings[0]);
       i++) {
    if (!strcasecmp(extension, icon_mappings[i].extension)) {
      return (IconResult){icon_mappings[i].icon, icon_mappings[i].color};
    }
  }
  return (IconResult){"", NULL};
}

#endif